// tb_lilliput.sv
// Testbench for lilliput_decoder using vectors generated by gen_vectors.py.
//
// tb_vectors.mem format (one per line):
//   <syndrome_hex> <obs_bit>

module tb_lilliput;

    localparam int N_DET = 40;
    localparam int N_LUT = 10701;

    logic [N_DET-1:0] syndrome;
    logic             pred_obs;

    // Instantiate decoder
    lilliput_decoder #(
        .N_DET(N_DET),
        .N_LUT(N_LUT),
        .LUT_SYND_FILE("lut_synd.mem"),
        .LUT_OUT_FILE ("lut_out.mem")
    ) dut (
        .syndrome(syndrome),
        .pred_obs(pred_obs)
    );

    int fd;
    int r;
    int total, logical_errors, missing_count;

    // We’ll also detect “missing” by re-checking a match in TB.
    // This duplicates work but helps match your Python stats.
    // (In real hardware you’d add a hit flag output.)
    logic hit;

    task automatic compute_hit(input logic [N_DET-1:0] s, output logic h);
        h = 1'b0;
        for (int i = 0; i < N_LUT; i++) begin
            if (s == dut.lut_synd[i]) begin
                h = 1'b1;
            end
        end
    endtask

    initial begin
        total = 0;
        logical_errors = 0;
        missing_count = 0;

        fd = $fopen("tb_vectors.mem", "r");
        if (fd == 0) begin
            $display("ERROR: Could not open tb_vectors.mem");
            $finish;
        end

        // Read line by line: syndrome_hex and obs_bit
        // We parse syndrome as hex into an integer then assign to syndrome vector.
        longint unsigned synd_int;
        int obs_bit;

        while (!$feof(fd)) begin
            r = $fscanf(fd, "%h %d\n", synd_int, obs_bit);
            if (r != 2) begin
                // skip malformed line
                void'($fgets("", fd));
                continue;
            end

            syndrome = synd_int[N_DET-1:0];

            // Let combinational settle
            #1;

            compute_hit(syndrome, hit);
            if (!hit) missing_count++;

            if (pred_obs !== obs_bit[0]) logical_errors++;
            total++;
        end

        $fclose(fd);

        $display("Total shots: %0d", total);
        $display("Logical errors (pure LUT): %0d", logical_errors);
        $display("Logical error rate (%%): %0f", (100.0 * logical_errors) / (total == 0 ? 1 : total));
        $display("Missing syndromes (no correction): %0d", missing_count);
        $display("Percent missing (%%): %0f", (100.0 * missing_count) / (total == 0 ? 1 : total));

        $finish;
    end

endmodule
